//! Oak Stylus Trading Engine - Native Stylus terminal for Arbitrum
//!
//! Atomic swaps by default (EVM-style); optional commit-reveal for MEV protection.
//! Institutional order types: limit orders, TP/SL, trailing stops.
//!
//! The crate is `no_std` on-chain, but uses `std` for tests.

#![cfg_attr(not(test), no_std)]

extern crate alloc;

// Stub for Stylus host hook when building on host (e.g. tests, non-WASM).
// On wasm32 the Stylus runtime provides native_keccak256; on x86_64 we must supply it.
#[cfg(not(target_arch = "wasm32"))]
#[no_mangle]
pub extern "C" fn native_keccak256(bytes: *const u8, len: usize, output: *mut u8) {
    use tiny_keccak::{Hasher, Keccak};
    let mut hasher = Keccak::v256();
    let mut out = [0u8; 32];
    let input = unsafe { core::slice::from_raw_parts(bytes, len) };
    hasher.update(input);
    hasher.finalize(&mut out);
    unsafe { core::ptr::copy_nonoverlapping(out.as_ptr(), output, 32) };
}

use alloc::vec::Vec;
use stylus_sdk::prelude::*;

/// Access Control by roles (DEFAULT_ADMIN_ROLE, PAUSER_ROLE, UPGRADER_ROLE).
pub mod access;
/// Protocol-wide constants (fees, limits, timing).
pub mod constants;
/// Shared error types and helpers.
pub mod errors;
/// Solidity-compatible event definitions.
pub mod events;
/// Persistent storage layout for the DEX.
pub mod state;
/// Pausable trait and implementation for OakDEX.
pub mod pausable;
/// TimelockController: queue -> delay -> execute.
pub mod timelock;
/// Core Engine: swap core, execution strategy (Atomic / Commit-Reveal), order execution.
pub mod engine;
/// Growth Engine: StakingRewards, Referral, Quest (EmissionEvent for indexer).
pub mod growth;
/// Intelligence Layer: Copy Trading, Signal Marketplace (EIP-712).
pub mod intelligence;
/// Core business logic (CPMM, atomic swap, optional commit‑reveal, admin).
pub mod logic;
/// ERC-20 token interface and transfer utilities.
pub mod token;
/// GMX-style vault logic (swap, leverage); internal use by OakSentinel.
pub mod vault;
/// Randomness utilities for Oak Bet (casino).
pub mod rng;

/// Entry point for the Oak Protocol contract.
///
/// @notice Main entry point invoked by the Stylus runtime.
/// @dev In a full deployment, this function would dispatch calls
///      generated by `cargo stylus` based on the ABI. For now it
///      simply returns an empty byte array to keep the contract
///      WASM-valid while we focus on core logic and architecture.
#[entrypoint]
pub fn main(_input: Vec<u8>) -> Result<Vec<u8>, Vec<u8>> {
    Ok(Vec::new())
}
