//! Oak Protocol - Next-generation DEX for Arbitrum Stylus
//!
//! This DEX implements a Commit-Reveal system to protect users from
//! front-running and sandwich attacks (MEV protection).
//!
//! The crate is `no_std` on-chain, but uses `std` for tests.

#![cfg_attr(not(test), no_std)]

extern crate alloc;

use alloc::vec::Vec;
use stylus_sdk::prelude::*;

/// Protocol-wide constants (fees, limits, timing).
pub mod constants;
/// Shared error types and helpers.
pub mod errors;
/// Solidity-compatible event definitions.
pub mod events;
/// Persistent storage layout for the DEX.
pub mod state;
/// Core business logic (CPMM, commit‑reveal, admin).
pub mod logic;
/// ERC-20 token interface and transfer utilities.
pub mod token;

/// Entry point for the Oak Protocol contract.
///
/// @notice Main entry point invoked by the Stylus runtime.
/// @dev In a full deployment, this function would dispatch calls
///      generated by `cargo stylus` based on the ABI. For now it
///      simply returns an empty byte array to keep the contract
///      WASM-valid while we focus on core logic and architecture.
#[entrypoint]
pub fn main(_input: Vec<u8>) -> Result<Vec<u8>, Vec<u8>> {
    Ok(Vec::new())
}
